# backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: transcribe-translate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/notyusheng/transcribe-translate-backend:cpu
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: transcribe-translate-backend
  namespace: transcribe-translate
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
