apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcribe-translate-backend
  labels:
    app: transcribe-translate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcribe-translate-backend
  template:
    metadata:
      labels:
        app: transcribe-translate-backend
    spec:
      containers:
      - name: transcribe-translate-backend
        image: ghcr.io/notyusheng/transcribe-translate-backend:cuda
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: whisper-models
          mountPath: /app/whisper_models
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: whisper-models
        emptyDir: {}
