apiVersion: v1
kind: Service
metadata:
  name: transcribe-translate-frontend
  namespace: transcribe-translate
spec:
  selector:
    app: transcribe-translate-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
