apiVersion: v1
kind: Service
metadata:
  name: transcribe-translate-nginx
  namespace: transcribe-translate
spec:
  selector:
    app: transcribe-translate-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
