apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcribe-translate-nginx
  namespace: transcribe-translate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcribe-translate-nginx
  template:
    metadata:
      labels:
        app: transcribe-translate-nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/notyusheng/transcribe-translate-nginx:latest
          ports:
            - containerPort: 80
